---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-10.04
  - name: ubuntu-12.04
  - name: centos-6.4
  - name: omnios-r151006c
    driver:
      box: omnios-r151006c
      box_url: http://omnios.omniti.com/media/OmniOS_r151006c-r1.box

suites:
  - name: client
    run_list:
      - recipe[chef-splunk::default]
      - recipe[test::default]
    attributes:
      splunk:
        accept_license: true

  - name: server
    run_list:
      - recipe[chef-splunk::default]
    attributes:
      splunk:
        is_server: true
        accept_license: true
        ssl_options:
          enable_ssl: true

  - name: disabled
    run_list:
      - recipe[chef-splunk::default]
    attributes:
      splunk:
        disabled: true
