# Use Travis's cointainer based infrastructure
sudo: required

addons:
  apt:
    sources:
      - chef-current-precise
    packages:
      - chefdk

# Don't `bundle install`
install: echo "skip bundle install"

branches:
  only:
    - kitchen-travis

services: docker

env:
  matrix:
    - INSTANCE=server-runas-splunk-ubuntu-1404
    - INSTANCE=client-runas-splunk-ubuntu-1404
    - INSTANCE=server-runas-splunk-centos-7
    - INSTANCE=client-runas-splunk-centos-7
    - INSTANCE=fpm-test-ubuntu-1404
    - INSTANCE=fpm-test-centos-7

# Ensure we make ChefDK's Ruby the default
before_script:
  # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142230889
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  # We have to install chef-sugar for ChefSpec
  - /opt/chefdk/embedded/bin/chef gem install chef-sugar
  - /opt/chefdk/embedded/bin/chef gem install kitchen-docker
script:
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/rubocop --version
  - /opt/chefdk/embedded/bin/rubocop
  - /opt/chefdk/embedded/bin/foodcritic --version
  - /opt/chefdk/embedded/bin/foodcritic . --exclude spec
  - /opt/chefdk/embedded/bin/rspec spec
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}
